version: "3.8"

services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: titivpn
    restart: unless-stopped

    environment:
      - PASSWORD=${PASSWORD}
      - WG_HOST=${WG_HOST}
      - WG_DEFAULT_DNS=1.1.1.1,8.8.8.8
      - WG_DEFAULT_ADDRESS=10.10.0.x

      # ✅ Auto-detect outgoing interface
      - WG_POST_UP=IFACE=$(ip route get 8.8.8.8 | awk '{print $5; exit}'); \
        iptables -t nat -A POSTROUTING -o $IFACE -j MASQUERADE
      - WG_POST_DOWN=IFACE=$(ip route get 8.8.8.8 | awk '{print $5; exit}'); \
        iptables -t nat -D POSTROUTING -o $IFACE -j MASQUERADE

    volumes:
      - ./wg-easy-data:/etc/wireguard

    ports:
      - "51820:51820/udp"
      # Comment this if you want to disable the Web UI (to save RAM):
      - "51821:51821/tcp"

    cap_add:
      - NET_ADMIN
      - SYS_MODULE

    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.forwarding=1
