version: "3.8"

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      # These are securely set via Fly.io secrets
      - WG_DEFAULT_DNS=1.1.1.1,8.8.8.8
      - WG_DEFAULT_ADDRESS=10.10.0.x

      # Auto detect network interface for NAT (✅ fly.io compatible)
      - WG_POST_UP=IFACE=$(ip route get 8.8.8.8 | awk '{print $5; exit}'); \
          iptables -t nat -A POSTROUTING -o $IFACE -j MASQUERADE; \
          ip6tables -t nat -A POSTROUTING -o $IFACE -j MASQUERADE
      - WG_POST_DOWN=IFACE=$(ip route get 8.8.8.8 | awk '{print $5; exit}'); \
          iptables -t nat -D POSTROUTING -o $IFACE -j MASQUERADE; \
          ip6tables -t nat -D POSTROUTING -o $IFACE -j MASQUERADE

    volumes:
      - ./wg-easy-data:/etc/wireguard

    ports:
      - "51820:51820/udp" # WireGuard port
      - "51821:51821/tcp" # Web UI

    restart: unless-stopped

    cap_add:
      - NET_ADMIN
      - SYS_MODULE

    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.forwarding=1
