version: "3.8"

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy

    environment:
      # === Required ===
      - WG_HOST=titivpn.fly.dev         # Replace with your fly.io hostname
      - PASSWORD=yoursecurepassword     # Set your admin password
      - WG_DEFAULT_ADDRESS=10.10.0.x    # Auto assigns 10.10.0.2, .3, etc.
      - WG_DEFAULT_DNS=1.1.1.1,8.8.8.8  # DNS for clients

      # === NAT: Masquerade outgoing traffic ===
      - WG_POST_UP=iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; \
        ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      - WG_POST_DOWN=iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE; \
        ip6tables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

    volumes:
      - ./wireguard:/etc/wireguard

    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"

    restart: unless-stopped

    cap_add:
      - NET_ADMIN
      - SYS_MODULE

    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.forwarding=1
