version: "3.8"

services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: titivpn
    restart: unless-stopped
    ports:
      - "51820:51820/udp"         # WireGuard port (VPN)
      - "51821:51821/tcp"         # Web UI port
    environment:
      - PASSWORD=     # Set your login password
      - WG_HOST=41.145.208.117              # ✅ Your public IP
    volumes:
      - ./wg-easy-data:/etc/wireguard       # Data storage
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
