version: "3.8"

services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: titivpn
    restart: unless-stopped
    ports:
      - "51820:51820/udp"         # WireGuard VPN port
      - "51821:51821/tcp"         # Web UI port
    environment:
      - PASSWORD=Tii071new123         # ✅ Set your login password
      - WG_HOST=66.241.125.45         # ✅ Your Fly.io public IP (NOT private IP)
      - WG_DEFAULT_DNS=1.1.1.1,8.8.8.8  # ✅ DNS for clients
      - WG_DEFAULT_ADDRESS=10.10.0.x   # ✅ Match client subnet
      - WG_ALLOWED_IPS=0.0.0.0/0       # ✅ Route all traffic

      # ✅ Auto-NAT fix for outbound internet access (dynamic interface detection)
      - WG_POST_UP=eth0=$(ip route get 8.8.8.8 | awk '{print $5}'); \
        iptables -t nat -A POSTROUTING -o $eth0 -j MASQUERADE; \
        ip6tables -t nat -A POSTROUTING -o $eth0 -j MASQUERADE
      - WG_POST_DOWN=eth0=$(ip route get 8.8.8.8 | awk '{print $5}'); \
        iptables -t nat -D POSTROUTING -o $eth0 -j MASQUERADE; \
        ip6tables -t nat -D POSTROUTING -o $eth0 -j MASQUERADE

    volumes:
      - ./wg-easy-data:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.forwarding=1
