app = "titivpn-eu"
primary_region = "ams"

[env]
# Add your WireGuard environment variables here if needed

[http_service]
internal_port = 51821
force_https = true
auto_start_machines = true
auto_stop_machines = true       # Sleep when idle
min_machines_running = 1        # Always keep at least 1 running
processes = ["app"]

[[services]]
internal_port = 51821
protocol = "udp"

  [[services.ports]]
  port = 51821
  handlers = ["udp"]

[[metrics]]
port = 9091
path = "/metrics"
