app = "titivpn"
primary_region = "jnb"

[env]
  # PASSWORD and WG_HOST are added securely later using `fly secrets set`

[http_service]
  internal_port = 51821
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1
  processes = ["app"]
