app = "titivpn"
primary_region = "jnb"

[env]
  # These will be injected securely using `flyctl secrets set`
  # PASSWORD and WG_HOST are stored safely

[http_service]
  internal_port = 51821
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1
  processes = ["app"]
